import LocalizedStrings from 'react-localization'

export let strings = new LocalizedStrings({
   en:{
      AddChild:"Add a Child",
      AddChildHeading1:"Enter information about the child you are adding to your household. We will contact you for additional information.",
      SsnLabel:"SSN",
      AppliedSsnLabel: "Have you applied for this child's SSN?",
      ReasonSsnLabel: "Reason why you don't have an SSN for this child?",
      ReportingPeriodLabel: "Select the reporting period",
      FirstNameLabel:"First Name",
      LastNameLabel:"Last Name",
      DOBLabel:"Date of Birth",
      GenderLabel:"Gender",
      ChildHaveSsnLabel:"Does this child have an SSN?",
      ButtonSave: "Save",
      ButtonCancel:'Cancel',
      IsMandatory:' must be entered.',
      FirstNameValidation:"First Name",
      LastNameValidation:'Last Name',
      ChildGreaterThan18Message:'The child must be under 18 years old. To add someone over 18, please select the “Add an adult” button on the previous page',
      ReportingPeriodMessage: 'Select the reporting Period',
      DOBFormatMessage:'The Date of Birth should be in date format mm/dd/yyyy',
      Blank:'',
      CannotBeInFuture: 'cannot be in the future',
      Gender: 'Gender',
      SSN: "SSN",
      IsNotValid:'is Not Valid',
      HaveAppliedForChildSSN: "Have you applied for SSN for this child?",
      ChildDoesNotHaveSSN: "Reason, why this child does not have an SSN",
      DuplicateChildValidation:"Child already exists in the household. Report any changes to your local DHS office."
    },
  es: {
    AddChild:"Añadir un niño",
    AddChildHeading1:"Ingrese información sobre el niño que está agregando a su hogar. DHS se pondrá en contacto con usted para obtener información adicional.",
    SsnLabel:"SSN",
    AppliedSsnLabel: "Ha solicitado el SSN de este niño?",
    ReasonSsnLabel: "Por qué no tiene un SSN para este niño?",
    ReportingPeriodLabel: "Seleccione el período de informe ",
    FirstNameLabel:"Nombre de pila",
    LastNameLabel:"Apellido",
    DOBLabel:"Fecha de nacimiento",
    GenderLabel:"Género",
    ChildHaveSsnLabel:"¿Tiene este niño un SSN? ",
    ButtonSave: "Salvar",
    ButtonCancel:'Cancelar',
    IsMandatory:'es obligatorio',
    FirstNameValidation:"Nombre de pila",
    LastNameValidation:'Apellido',
    DOBValidation:'Fecha de nacimiento',
    ChildGreaterThan18Message:'El niño debe ser menor de 18 años. Para agregar a alguien mayor de 18 años, seleccione el botón "Agregar un adulto" en la página anterior.',
    ReportingPeriodMessage: 'Seleccione el período de informe',
    DOBFormatMessage:'La fecha de nacimiento debe estar en formato de fecha mm / dd / aaaa',
    Blank:'',
    CannotBeInFuture: 'no puede ser en el futuro',
    Gender: 'Género',
    ChildHaveSSN: 'Hace este niño un SSN',
    SSN: "SSN",
    IsNotValid:'no es válido',
    HaveAppliedForChildSSN: "Ha solicitado el número de Seguro Social de este niño",
    ChildDoesNotHaveSSN: "Motivo, por qué este niño no tiene un número de seguro social",
    DuplicateChildValidation:"Child already exists in the household. Report any changes to your local DHS office."
    }
  });
  var userLang = navigator.language || navigator.userLanguage;
  strings.setLanguage(userLang)