import LocalizedStrings from 'react-localization'

export let strings = new LocalizedStrings({
  en:{
      home:"Home",
      welcome:"Welcome",
      info: "Update Your Information",
      logout:"Logout",
      currentReportPeriod:"Current Reporting Periods",
      selectmthbelow:"Select a reporting month below.",
      status: "Status",
      requiredtowok:"Required to report work activities",
      reprtperd:"Reporting Period",
      counhrs:"Total Hours",
      rmnhrs:" Total Remaining Hours",
      annsumm:"Annual Summary",
      intrmprd:"Interim Period",
      complaint:"Compliant",
      exempt:"Exempt",
      ememptPeriod: "Exemption Period:",
      exemption: 'Exemption:',
      noncomplaint:"Non-Compliant",
      monsummary:"Monthly Summary",
      arworksinfo:"Click here to learn about the work requirement and find out if you are required to report work activities.",
      help:"Do you want to work, but need help?",
      EXMT: 'Exempt',
      NSW : "Not Subject to Work Requirement",
      IIP:'Interim Period',
      IAP: 'Interim Period',
      IRP: 'Interim Period',
      IAAP: 'Interim Period',
      RTW: 'Required to Report Work Activities',
      COMP: 'Compliant',
      NCM: 'Non-Compliant',
      NCM1: 'Non-Compliant',
      NCM2: 'Non-Compliant',
      NCM3: 'Non-Compliant',
      EXAIAN: 'Alaskan Native/American Indian',
      TEACASHEX : 'Receiving TEA Cash Assistance',
      EXEC : 'Exempt for Extenuating Circumstances',
      EXSNAP: 'SNAP Exemption',
      EXFS: 'Full Time Student Exemption',
      EXMF: 'Medically Frail Exemption',
      EXDM : 'Dependent Minor Exemption',
      EXEH : 'Employed Eighty Hours Exemption',
      EXPR : 'Pregnant Exemption',
      EXUN : 'Unemployed Exemption',
      EXED : 'Full-time Educatoin , Job Training, or Vocational Training Exemption',
      EXIC : 'Incapacitated Care Exemption',
      EXIS : 'Incapacitated Self Exemption',
      EXAL : 'Participation Alcohol or Drug Exemption',
      reporting_period_section: 'You do not have Arkansas Works Insurance during a current reporting period.',
      intrmprdtooltip: 'The work requirement does not apply to you during an interim period.',
      complainttooltip:'You are required to report work activities and you reported at least 80 hours of work activities for the month.',
      exempttooltip:'You are not required to report work activities during months that you are exempt.',
      noncomplainttooltip:'You are required to report work activities and you did not report at least 80 hours of work activities for the month.<br /> Your Arkansas Works coverage will close at the end of your third month of non-compliance and you will not be able to regain Arkansas Works coverage for the rest of the calendar year.'
      },
  es: {
      home:"Casa",
      welcome:"Bienvenido",
      info: "Actualice su información",
      logout:"Cerrar sesión",
      currentReportPeriod:"Períodos de Reporte Actuales",
      selectmthbelow:"Seleccione un mes de reporte por debajo",
      status: "Estado",
      requiredtowok:"Requerido para reportar actividades de trabajo",
      reprtperd:"Período de información",
      counhrs:"Horas Contables",
      rmnhrs:"Horas Restantes",
      annsumm:"Resumen Anual",
      intrmprd:"Periodo intermedio",
      complaint:"Obediente",
      exempt:"Eximir",
      noncomplaint:"Non-Compliant",
      monsummary:"Resumen mensual",
      arworksinfo:"Haga clic aquí para obtener más información sobre el requisito de trabajo y averigüe si se le requiere trabajar.",
      help:"¿Quieres trabajar, pero necesitas ayuda?"
    }
  });
  var userLang = navigator.language || navigator.userLanguage;
  strings.setLanguage(userLang)