import LocalizedStrings from 'react-localization'

export let strings = new LocalizedStrings({
    en: {
        heading:"Job Search",
        headerNote:"Enter information about Job Search. You may count up to 39 total hours from Job Search and Job Search Training in each month.",
        datesLabel:"Enter job search date(s)",
        numberOfJobContact:"How many job contacts did you make? ",
        receiveHelpJobSearch:"Are you participating in a program that helps you search for a job? ",
        programName:"Program Name ",
        contactName:"Contact Name ",
        save: "Save",
        cancel: "Cancel",
        IsMandatory:' must be entered.',
        FromDate: 'Start Date ',
        ToDate: 'End Date ',
        ProgramName: 'Program Name ',
        ContactName: 'Contact Name ',
        Street1: 'Address Line 1 ',
        City: 'City ',
        State: 'State ',
        ZipCode: 'Zip Code ',
        InValidZipCode: 'The Zip Code entered is not in a valid format.',
        FormatZipCode: ' It must either be in the following five digit format xxxxx or the following nine digit format xxxxx-xxxx.',
        PhoneNumber: 'Phone Number',
        AreaCode: 'Area Code',
        InvalidPhoneNumber: 'The Phone Number entered is not in a valid format. It must be in the following ten digit format ',
        FormatPhoneNumber: '(Area code - Phone number) xxx-xxxxxxx.',
        DOBValidation: ' cannot be before your Date Of Birth',
        DifferentMonthValidation: ' and End Date must be in the same month',
        StartDateValidation: ' cannot be after End Date'
    },
    es: {
        heading:"Búsqueda de trabajo",
        headerNote:"Ingrese información sobre la búsqueda de trabajo. Usted puede contar hasta 39 horas totales de Entrenamiento de Búsqueda de Empleo y Búsqueda de Empleo en cada mes.",
        fromDate: "Partir de la fecha*",
        toDate:"Hasta la fecha*",
        numberOfJobContact:"Cuantos contactos de trabajo hiciste*",
        receiveHelpJobSearch:"¿Está participando en un programa que le ayuda a buscar un trabajo? *",
        programName:"Nombre del programa",
        contactName:"Nombre de contacto",
        save: "Salvar",
        cancel: "Cancelar",
        IsMandatory:'es obligatorio',
        FromDate: 'Partir de la fecha ',
        ToDate: 'Hasta la fecha ',
        NumberOfContacts:'Número de contactos de trabajo ',
        ProgramParticipation: 'Estás participando en un programa ',
        ProgramName: 'Nombre del programa ',
        ContactName: 'Nombre de contacto ',
        Street1: 'Dirección Línea 1 ',
        City: 'Ciudad ',
        State: 'Estado ',
        ZipCode: 'Código postal ',
        InValidZipCode: 'El código postal ingresado no está en un formato válido.',
        FormatZipCode: ' Debe estar en el siguiente formato de cinco dígitos xxxxx o el siguiente formato de nueve dígitos xxxxx-xxxx.',
        PhoneNumber: 'El numero de telefono ',
        InvalidPhoneNumber: 'El número de teléfono ingresado no está en un formato válido. Debe estar en el siguiente formato de diez dígitos ',
        FormatPhoneNumber: '(Código de área - Número de teléfono) xxx-xxxxxxx.',
        DifferentMonthValidation: ' y la fecha de finalización debe estar en el mismo mes',        
        StartDateValidation: ' no puede ser después de la fecha de finalización'
    }
});
var userLang = navigator.language || navigator.userLanguage;
strings.setLanguage(userLang)