import LocalizedStrings from 'react-localization'

export let strings = new LocalizedStrings({
    en: {
		  home:"Home",
		  welcome:"Welcome",
		  info: "Update Your Information",
		  logout:"Logout",
        //Summary Details
        status : 'Status: ',
        totalHours: 'Total Hours: ',
        totalRemainingHours: 'Total Remaining Hours: ',
        exemption: 'Exemption: ',
        exemptionPeriod: 'Exemption Period: ',
        EXMT : 'Exempt',
        NSW : "Not Subject to Work Requirement",
        IIP :'Interim Period',
        IAP : 'Interim Period',
        IRP : 'Interim Period',
        IAAP : 'Interim Period',
        RTW : 'Required to Report Work Activities',
        COMP : 'Compliant',
        NCM : 'Non-Compliant',
        NCM1 : 'Non-Compliant',
        NCM2 : 'Non-Compliant',
        NCM3 : 'Non-Compliant',
        EXAIAN : 'Alaskan Native/American Indian',
        TEACASHEX : 'Receiving TEA Cash Assistance',
        EXEC : 'Exempt for Extenuating Circumstances',  
        EXSNAP : 'SNAP Exemption',
        EXFS: 'Full Time Student Exemption',
        EXMF: 'Medically Frail Exemption',
        EXDM : 'Dependent Minor Exemption',
        EXEH : 'Employed Eighty Hours Exemption',
        EXPR : 'Pregnant Exemption',
        EXUN : 'Unemployed Exemption',
        EXED : 'Education Job Training Exemption',
        EXIC : 'Incapacitated Care Exemption',
        EXIS : 'Incapacitated Self Exemption',
        EXAL : 'Participation Alcohol or Drug Exemption',
        //Submitted evidences title
        TITLE_IT26001: 'Income',
        TITLE_IT26008: 'Income',
        TITLE_IT26017: 'Income',
        TITLE_IT26015: 'Unemployment Insurance',
        TITLE_DT1: 'Special Health Needs',
        TITLE_DT2: 'Special Health Needs',
        TITLE_DT26301: 'Special Health Needs',
        TITLE_EEFDT2: 'Special Health Needs',
        TITLE_EEFDET0010: 'Special Health Needs',
        TITLE_DET0026008: 'Pregancy',
        TITLE_EEF01: 'School or Vocational Training',
        TITLE_ST3: 'School or Vocational Training',
        TITLE_EEF02: 'School or Vocational Training',
        TITLE_EEF03: 'School or Vocational Training',
        TITLE_ST12: 'School or Vocational Training',
        TITLE_ST5: 'School or Vocational Training',
        TITLE_ST7: 'School or Vocational Training',
        TITLE_EEFDET0017: 'Caring for someone who cannot care for him/herself',
        TITLE_EEFDET0016: 'Alcohol or Drug Treatment program',
        TITLE_EEFDET0021: 'Job Search',
        TITLE_EEFDET0018: 'Job Search Training',
        TITLE_EEFDET0019: 'Volunteer',
        TITLE_EEFDET0025: 'Compliant with SNAP Plan',
        TITLE_EEFDET0027: 'Child living in my home',
        TITLE_EEFDET0020: 'Health Education Class',
        //Submitted evidences Display Line1 Value
        DISPLAY1_IT26001: 'Your reported income divided by Arkansas minimum wage = work activity hours.',
        DISPLAY1_IT26008: 'Your reported income divided by Arkansas minimum wage = work activity hours.',
        DISPLAY1_IT26017: 'Your reported income divided by Arkansas minimum wage = work activity hours.',
        AMOUNT: 'Amount: $',
        CHILD: 'Child: ',
        CHLD_EXEMP : 'Child Exemption',
        DISPLAY1_DT1: 'Blind',
        DISPLAY1_DT2: 'I have a disability',
        DISPLAY1_DT26301: 'Need help with daily activities',
        DISPLAY1_EEFDT2: 'Short term disability',
        DISPLAY1_EEFDET0010: 'Living in a medical institution',
        INSTITUTION: 'Institution: ',
        DUE_DATE:'Due Date: ',
        SCHOOL_ORGANIZATION:'School / Organization Name: ',
        NAME:'Name: ',
        PERSON_CARE_FOR:'Person you care for: ',
        PROGRAM_FACILITY_NAME:'Program/Facility Name: ',
        DISPLAY1_EEFDET0021: '1 reported job contact = 3 work activity hours. You may count up to 39 total hours from Job Search and Job search Training each month.',
        DISPLAY1_EEFDET0018: '1 reported hour = 1 work activity hour. You may count up to 39 total hours from Job Search and Job search Training each month.',
        DISPLAY1_EEFDET0019: '1 reported hour = 1 work activity hour.',
        DISPLAY1_EEFDET0020: '1 reported hour = 1 work activity hour. You may count up to 20 hours each year from this activity.',
        //Submitted evidences Display Line2 Value
        EMPLOYER:'Employer: ',
        HOURS:'Hours: ',
        SUBMITTED:'Submitted',
        END_OF_POSTPARTUM:'End of post-partum: ',
        DISPLAY2_EEF01:'1 hour of instruction =  2.5* work activity hours.',
        DISPLAY2_ST3:'1 reported hour =  2 work activity hours.',
        DISPLAY2_EEF02:'1 reported hour =  1 work activity hour.',
        DISPLAY2_EEF03:'1 hour of instruction =  2 work activity hours.',
        DISPLAY2_ST12:'1 credit hour =  2.5* work activity hours.',
        DISPLAY2_ST5:'1 hour of instruction =  2.5* work activity hours.',
        DISPLAY2_ST7:'1 credit hour =  2.5* work activity hours.',
        ORGANIZATION:'Organization: ',
        CLASS_NAME:'Class Name: ',
		ButtonHome:'Home',
		ButtonReportExemptionWorkActivity:'Report Exemption/Work Activity',
        ButtonSubmit:'Submit',
        HMIT1: 'Nursing Home',
        HMIT2: 'Intermediate Care Facility for the Intellectually Disabled', 
        HMIT3: 'Arkansas State Hospital',
        HMIT4: 'Arkansas Health Center',
        HMIT5: 'Human Development Center',
        IncomeHours: 'Work activity hours will be calculated after submission.',
        MONTHLY: '(Monthly)',
        DISPLAY1_IT26001_END_INCOME: 'You are reporting your income from this Employer has ended.',
        DISPLAY1_IT26008_END_INCOME: 'You are reporting your income from this source has ended.',
        DISPLAY1_IT26017_END_INCOME: 'You are reporting your income from this source has ended.',
        DISPLAY1_IT26015_END_INCOME: 'You are reporting your income from this source has ended.',
        DISPLAY2_IT26017_END_INCOME: 'Farming or fishing Income',
        DISPLAY2_IT26015_END_INCOME: 'Unemployment Insurance',
        DISPLAY2_IT26008_END_INCOME: 'Net Self Employment Income',
        TITLE_END_INCOME: 'Income',
        END_DATE: 'End Date: ',
        TYPE: 'Type: '
          
    },
    es: {
        home:"Casa",
        welcome:"Bienvenido",
        info: "Actualiza tu información",
        logout:"Cerrar sesión",
      //Summary Details
      status : 'Estado : ',
      totalHours: 'Horas totales : ',
      totalRemainingHours: 'Total de horas restantes : ',
      exemption: 'Exención : ',
      exemptionPeriod: 'Período de Exención : ',
      EXMT : 'Eximir',
      NSW : "No sujeto a requisitos de trabajo",
      IIP :'Periodo intermedio',
      IAP : 'Periodo intermedio',
      IRP : 'Periodo intermedio',
      IAAP : 'Periodo intermedio',
      RTW : 'Obligatorio para reportar actividades de trabajo',
      COMP : 'Obediente',
      NCM : 'No compatible',
      NCM1 : 'No compatible',
      NCM2 : 'No compatible',
      NCM3 : 'No compatible',
      EXAIAN : 'Nativo de Alaska / indio americano',
      EXSNAP : 'Exención de SNAP',
      EXFS: 'Exención de tiempo completo para estudiantes',
      EXMF: 'Médicamente exención frágil',
      EXDM : 'Exención Menor Dependiente',
      EXEH : 'Empleamos la Exención de las Ochenta Horas',
      EXPR : 'Exención de embarazo',
      EXUN : 'Exención por desempleo',
      EXED : 'Exención de capacitación laboral para la educación',
      EXIC : 'Exención de cuidado incapacitado',
      EXIS : 'Autoexención incapacitada',
      EXAL : 'Participación Alcohol o exención de drogas',
      //Submitted evidences title
      TITLE_IT26001: 'Ingresos',
      TITLE_IT26008: 'Ingresos',
      TITLE_IT26017: 'Ingresos',
      TITLE_IT26015: 'k',
      TITLE_DT1: 'Necesidades especiales de salud',
      TITLE_DT2: 'Necesidades especiales de salud',
      TITLE_DT26301: 'Necesidades especiales de salud',
      TITLE_EEFDT2: 'Necesidades especiales de salud',
      TITLE_EEFDET0010: 'Necesidades especiales de salud',
      TITLE_DET0026008: 'El embarazo',
      TITLE_EEF01: 'Escuela o Formación Profesional',
      TITLE_ST3: 'Escuela o Formación Profesional',
      TITLE_EEF02: 'Escuela o Formación Profesional',
      TITLE_EEF03: 'Escuela o Formación Profesional',
      TITLE_ST12: 'Escuela o Formación Profesional',
      TITLE_ST5: 'Escuela o Formación Profesional',
      TITLE_ST7: 'Escuela o Formación Profesional',
      TITLE_EEFDET0017: 'Cuidando a una persona incapacitada',
      TITLE_EEFDET0016: 'Programa de tratamiento de alcohol o drogas',
      TITLE_EEFDET0021: 'Búsqueda de trabajo',
      TITLE_EEFDET0018: 'Formación en búsqueda de empleo',
      TITLE_EEFDET0019: 'Voluntario',
      TITLE_EEFDET0025: 'Cumple con el plan SNAP',
      TITLE_EEFDET0020: 'Clase de educación en salud',
      //Submitted evidences Display Line1 Value
      DISPLAY1_IT26001: 'Su ingreso reportado dividido por el salario mínimo de Arkansas = horas de actividad laboral.',
      DISPLAY1_IT26008: 'Su ingreso reportado dividido por el salario mínimo de Arkansas = horas de actividad laboral.',
      DISPLAY1_IT26017: 'Su ingreso reportado dividido por el salario mínimo de Arkansas = horas de actividad laboral.',
      AMOUNT: 'Cantidad : ',
      DISPLAY1_DT1: 'Ciego',
      DISPLAY1_DT2: 'Tengo una discapacidad',
      DISPLAY1_DT26301: 'Necesita ayuda con las actividades diarias',
      DISPLAY1_EEFDT2: 'Invalidez a corto plazo',
      DISPLAY1_EEFDET0010: 'Viviendo en una institución médica',
      INSTITUTION: 'Institución : ',
      DUE_DATE:'Fecha de vencimiento : ',
      SCHOOL_ORGANIZATION:'Nombre de la escuela / organización : ',
      NAME:'Nombre : ',
      PERSON_CARE_FOR:'Persona que te importa : ',
      PROGRAM_FACILITY_NAME:'Nombre del Programa / Facilidad : ',
      DISPLAY1_EEFDET0021: '1 contacto laboral = 3 horas de actividad laboral. Usted puede contar hasta 39 horas totales de búsqueda de empleo y formación de búsqueda de empleo cada mes.',
      DISPLAY1_EEFDET0018: '1 hora reportada = 1 hora de actividad laboral. Usted puede contar hasta 39 horas totales de búsqueda de empleo y formación de búsqueda de empleo cada mes.',
      DISPLAY1_EEFDET0019: '1 hora reportada = 1 hora de actividad laboral.',
      DISPLAY1_EEFDET0020: '1 hora reportada = 1 hora de actividad laboral. Usted puede contar hasta 20 horas al año de esta actividad.',
      //Submitted evidences Display Line2 Value
      EMPLOYER:'Empleador : ',
      HOURS:'Horas de trabajo : ',
      SUBMITTED:'Presentada',
      END_OF_POSTPARTUM:'Fin del postparto : ',
      DISPLAY2_EEF01:'1 hora de instrucción = 2.5 * horas de actividad laboral.',
      DISPLAY2_ST3:'1 hora reportada = 2 horas de actividad laboral.',
      DISPLAY2_EEF02:'1 hora informada = 1 hora de actividad laboral.',
      DISPLAY2_EEF03:'1 hora de instrucción = 2 horas de actividad laboral.',
      DISPLAY2_ST12:'1 hora de crédito = 2.5 * horas de actividad laboral.',
      DISPLAY2_ST5:'1 hora de instrucción = 2.5 * horas de actividad laboral.',
      DISPLAY2_ST7:'1 hora de crédito = 2.5 * horas de actividad laboral.',
      ORGANIZATION:'Organización : ',
      CLASS_NAME:'Nombre de la clase : ',
      ButtonHome:'Casa',
      ButtonReportExemptionWorkActivity:'Informe Exención / Actividad laboral',
      ButtonSubmit:'Enviar',
      IncomeHours: 'Las horas de actividad laboral se calcularán después de la presentación'
        
    }
});
var userLang = navigator.language || navigator.userLanguage;
strings.setLanguage(userLang)